spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: api-perros
  datasource:
    url: jdbc:mysql://localhost:3306/perros?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: Carmelita23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 3000
  
fiordex:
  carpeta:
    fotos: web-files